### ISSUE TITLE
Release Build Workflow Action

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#52]
@orchetect Right now we have a [build.yml](https://github.com/TheAcharya/MarkersExtractor/blob/main/.github/workflows/build.yml) to check and test the code.

I am wondering if we can create a release build workflow as well? Something similar to [this](https://github.com/TheAcharya/csv2notion-neo/blob/master/.github/workflows/release_github.yml). 

That way we easily [build the binaries and release them](https://github.com/TheAcharya/csv2notion-neo/actions/workflows/release_github.yml) via actions.

**Comment by orchetect** [comment]
Noted. There are a [number of manual steps involved](https://github.com/TheAcharya/MarkersExtractor/blob/main/CONTRIBUTING.md#releases) currently but yes, it may be possible to automate a large portion of the process.

**Comment by IAmVigneswaran** [comment]
To simply the release build steps -

- Maybe we edit and update the CHANGELOG.md manually?

- Not sure if this could be possible. We can have a `version.txt` file. Something similar to [this](https://github.com/TheAcharya/csv2notion-neo/blob/master/csv2notion_neo/version.py). We can edit and increase the version number if we want to officially push a build to the release page. Else, we can just grab the build binaries from the Action tab for internal testing.

**Comment by orchetect** [comment]
> edit and update the CHANGELOG.md manually

We already do, and that won't change.

> We can have a version.txt file.

I do something similar in other repos, but for the time being I have moved the CLI's version string to its own swift file which will make it simpler to update through automated scripts.

**Comment by IAmVigneswaran** [comment]
@orchetect I tried to create a release_github.yml using ChatGPT. 😅

It would extract version number from the `Version.swift` file. Not sure if it would work.

```yml
name: release_github

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release after build'
        required: true
        default: 'no'
  push:
    branches:
      - main

env:
  SWIFT_VERSION: '5.5'  # Define your desired Swift version here
  PACKAGE_NAME: markers-extractor-cli
  WORKSPACE_PATH: 'MyProject.xcodeproj'  # Define the path to your Xcode project or workspace here

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract version number
        id: extract_version
        run: |
          CLI_VERSION=$(sed -n 's/.*let cliVersion = "\(.*\)".*/\1/p' Version.swift)
          echo "CLI_VERSION=$CLI_VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Set up Swift
        uses: actions/setup-swift@latest
        with:
          swift-version: ${{ env.SWIFT_VERSION }}

      - name: Build Swift project
        run: |
          swift build --configuration release -Xswiftc "-DVERSION=\(CLI_VERSION)" -Xswiftc "-workspace" -Xswiftc "${{ env.WORKSPACE_PATH }}"
        working-directory: ${{ env.PACKAGE_NAME }}

      - name: Create release archive
        run: |
          mkdir dist
          cp .build/release/${{ env.PACKAGE_NAME }} dist/
          cd dist
          zip -r ${{ env.PACKAGE_NAME }}-${{ env.CLI_VERSION }}.zip ${{ env.PACKAGE_NAME }}
        working-directory: ${{ env.PACKAGE_NAME }}

      - name: Save release artifact
        uses: actions/upload-artifact@v2
        with:
          name: release_dist
          path: dist
```
